package com.rideaustin.api.model;

/**
 * Created by viacheslavokolitiy on 09.07.2016.
 */

public enum RideStatus {

    NO_AVAILABLE_DRIVER("NO_AVAILABLE_DRIVER"),
    HANDSHAKE("HANDSHAKE"),
    REQUESTED("REQUESTED"),
    RIDER_CANCELLED("RIDER_CANCELLED"),
    DRIVER_CANCELLED("DRIVER_CANCELLED"),
    ADMIN_CANCELLED("ADMIN_CANCELLED"),
    DRIVER_ASSIGNED("DRIVER_ASSIGNED"),
    DRIVER_REACHED("DRIVER_REACHED"),
    ACTIVE("ACTIVE"),
    COMPLETED("COMPLETED"),

    GO_OFFLINE("GO_OFFLINE"),
    CUSTOM_MESSAGE("CUSTOM_MESSAGE"),
    SURGE_AREA_UPDATE("SURGE_AREA_UPDATE"),
    SURGE_AREA_UPDATES("SURGE_AREA_UPDATES"),
    RATING_UPDATED("RATING_UPDATED"),
    RIDER_LOCATION_UPDATED("RIDER_LOCATION_UPDATED"),
    RIDER_COMMENT_UPDATED("RIDER_COMMENT_UPDATED"),
    END_LOCATION_UPDATED("END_LOCATION_UPDATED"),
    RIDE_STACKED_REASSIGNED("RIDE_STACKED_REASSIGNED"),

    // custom events
    CAR_CATEGORY_CHANGE("CAR_CATEGORY_CHANGE"),
    RIDE_UPGRADE_ACCEPTED("RIDE_UPGRADE_ACCEPTED"),
    RIDE_UPGRADE_DECLINED("RIDE_UPGRADE_DECLINED"),
    DRIVER_TYPE_UPDATE("DRIVER_TYPE_UPDATE"),

    QUEUED_AREA_ENTERING("QUEUED_AREA_ENTERING"),
    QUEUED_AREA_UPDATE("QUEUED_AREA_UPDATE"),
    QUEUED_AREA_LEAVING("QUEUED_AREA_LEAVING"),
    QUEUED_AREA_LEAVING_INACTIVE("QUEUED_AREA_LEAVING_INACTIVE"),
    QUEUED_AREA_LEAVING_PENALTY("QUEUED_AREA_LEAVING_PENALTY"),
    QUEUED_AREA_LEAVING_RIDE("QUEUED_AREA_LEAVING_RIDE"),

    // Artificial in app state
    UNKNOWN("UNKNOWN"),
    RIDE_REQUEST_ERROR("ERROR"),
    FINISHED("FINISHED");

    String status;

    RideStatus(String status) {
        this.status = status;
    }
}